---
#list of available Proxmox Container templates can be found at:
#/usr/bin/pveam available

- name: Download Proxmox Container Template
  delegate_to: localhost
  community.proxmox.proxmox_template:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    storage: "{{ proxmoc_ct_template_storage }}"
    content_type: vztmpl
    template: "{{ proxmox_ct_ostemplate | regex_replace('^'+proxmoc_ct_template_storage+':vztmpl/', '') }}"

- block:
    - name: Get Container vmid
      delegate_to: localhost
      community.proxmox.proxmox_vm_info:
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
        api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
        api_password: "{{ proxmox_api_password | default(omit) }}"
        node: "{{ proxmox_node }}"
        type: lxc
      register: proxmox_vm_info
      when:
        - proxmox_vmid is not defined
      retries: 3
      delay: 3

    - name: Set Proxmox Container vmid
      set_fact:
        proxmox_vmid: "{{ (proxmox_vm_info.proxmox_vms | selectattr('name', 'equalto', proxmox_ct_hostname) | list | first).vmid }}"
      when:
        - (proxmox_vm_info.proxmox_vms | selectattr('name', 'equalto', proxmox_ct_hostname) | list) | length > 0

  rescue:
    - name: No container found
      ansible.builtin.debug:
        msg: "Container with hostname {{ proxmox_ct_hostname }} not found."
  when: proxmox_vmid is not defined

- name: Create mount points on host
  delegate_to: "{{ proxmox_node_host }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  vars:
    host_paths: "{{ proxmox_ct_mount_volumes | default([]) | map(attribute='host_path') | list }}"
  loop: "{{ host_paths }}"
  loop_control:
    label: "{{ item }}"

- name: Create Proxmox Container
  delegate_to: localhost
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    validate_certs: "{{ proxmox_validate_certs | default(omit) }}"
    vmid: "{{ proxmox_vmid | default(omit) }}"
    node: "{{ proxmox_node }}"
    hostname: "{{ proxmox_ct_hostname }}"
    searchdomain: "{{ proxmox_ct_searchdomain | default(omit) }}"
    nameserver: "{{ proxmox_ct_nameserver | default(omit) }}"
    ostemplate: "{{ proxmox_ct_ostemplate | default(proxmox_ct_ostemplate_default) }}"
    ostype: "{{ proxmox_ct_ostype | default(proxmox_ct_ostype_default) }}"
    cpus: "{{ proxmox_ct_cpus | default(omit) }}"
    cores: "{{ proxmox_ct_cores | default(proxmox_ct_cores_default) }}"
    cpuunits: "{{ proxmox_ct_cpuunits | default(omit) }}"
    timezone: "{{ proxmox_ct_timezone | default(proxmox_ct_timezone_default) }}"
    memory: "{{ proxmox_ct_memory | default(proxmox_ct_memory_default) }}"
    swap: "{{ proxmox_ct_swap | default(omit) }}"
    tags: "{{ proxmox_ct_tags | default(omit) }}"
    description: "{{ proxmox_ct_description | default(omit) }}"
    unprivileged: "{{ proxmox_ct_unprivileged | default(proxmox_ct_unprivileged_default) }}"
    storage: "{{ proxmox_ct_storage | default(proxmox_ct_storage_default) }}"
    mount_volumes: "{{ proxmox_ct_mount_volumes | default(omit) }}"
    disk_volume: "{{ proxmox_ct_disk_volume | default(omit) }}"
    onboot: "{{ proxmox_ct_onboot | default(proxmox_ct_onboot_default) }}"
    hookscript: "{{ proxmox_ct_hookscript | default(omit) }}"
    startup: "{{ proxmox_ct_startup | default(omit) }}"
    password: "{{ proxmox_ct_password }}"
    pubkey: "{{ proxmox_ct_pubkey | default(omit) }}"
    netif: "{{ proxmox_ct_netif | default(proxmox_ct_netif_default) }}"
    features: "{{ proxmox_ct_features | default(omit) }}"
    state: "{{ proxmox_ct_state | default('present') }}"
  register: ct_creation_result
  retries: 5
  delay: "{{ 15 | random(start=1) }}"

- name: Set facts for Proxmox Container
  set_fact:
    proxmox_vmid: "{{ ct_creation_result.vmid }}"
  when: ct_creation_result.vmid is defined

- name: Wait for container to be created
  delegate_to: localhost
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    type: lxc
  when: ct_creation_result.changed
  register: proxmox_vm_info
  retries: 5
  delay: 15
  until: proxmox_ct_hostname in proxmox_vm_info.proxmox_vms | map(attribute='name') | list

- name: Set Proxmox Container Extra Configuration
  delegate_to: "{{ proxmox_node_host }}"
  ansible.builtin.blockinfile:
    path: "/etc/pve/lxc/{{ proxmox_vmid }}.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ item.marker_name }}"
    block: "{{ item.extra_config | default('') }}"
    insertafter: EOF
  loop: "{{ proxmox_ct_host_extra_config | default([]) }}"
  when:
    - proxmox_vmid is defined
    - proxmox_ct_host_extra_config is defined
    - proxmox_ct_host_extra_config | length > 0
  register: ct_config_result
  notify: Restart Proxmox Container

- name: Start Proxmox Container
  delegate_to: localhost
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    vmid: "{{ proxmox_vmid }}"
    node: "{{ proxmox_node }}"
    state: started
  when:
    - proxmox_vmid is defined

- name: Wait for Proxmox Container to be ready
  delegate_to: localhost
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    type: lxc
    vmid: "{{ proxmox_vmid }}"
  register: proxmox_vm_info
  retries: 5
  delay: 15
  until: proxmox_vm_info.proxmox_vms[0].status == 'running'
  when: not ansible_check_mode
