---
# list of available Proxmox Container templates can be found at:
# /usr/bin/pveam available

- name: Download Proxmox Container Template
  delegate_to: localhost
  community.proxmox.proxmox_template:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    storage: "{{ proxmoc_ct_template_storage }}"
    content_type: vztmpl
    template: >-
      {{ proxmox_ct_combined['ostemplate'] |
        regex_replace('^' + proxmoc_ct_template_storage + ':vztmpl/', '') }}

- name: Get Container vmid if not defined
  when: proxmox_vmid is not defined
  block:
    - name: Get Container vmid
      delegate_to: localhost
      community.proxmox.proxmox_vm_info:
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
        api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
        api_password: "{{ proxmox_api_password | default(omit) }}"
        node: "{{ proxmox_node }}"
        type: lxc
      register: proxmox_vm_info
      when:
        - proxmox_vmid is not defined
      retries: 3
      delay: 3

    - name: Set Proxmox Container vmid
      ansible.builtin.set_fact:
        proxmox_vmid: "{{ (names | first).vmid }}"
      vars:
        names: >-
          {{ proxmox_vm_info.proxmox_vms |
            selectattr('name', 'equalto', proxmox_ct_combined['hostname']) | list }}
      when:
        - names | length > 0

  rescue:
    - name: No container found
      ansible.builtin.debug:
        msg: "Container with hostname {{ proxmox_ct_combined['hostname'] }} not found."

- name: Create mount points on host
  delegate_to: "{{ proxmox_node_host }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  vars:
    host_paths: >-
      {{ proxmox_ct_combined['mount_volumes'] | default([]) |
      map(attribute='host_path') | list }}
  loop: "{{ host_paths }}"
  loop_control:
    label: "{{ item }}"

- name: Create Proxmox Container
  delegate_to: localhost
  community.proxmox.proxmox: "{{ proxmox_ct_combined }}"
  register: ct_creation_result
  retries: 5
  delay: "{{ 15 | random(start=1) }}"

- name: Set facts for Proxmox Container
  ansible.builtin.set_fact:
    proxmox_vmid: "{{ ct_creation_result.vmid }}"
  when: ct_creation_result.vmid is defined

- name: Get Proxmox Container info
  delegate_to: localhost
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    type: lxc
  register: proxmox_vm_info
  retries: 5
  delay: 15
  until: >-
    proxmox_ct_combined['hostname'] in proxmox_vm_info.proxmox_vms |
    map(attribute='name') | list

- name: Set Proxmox Container Extra Configuration
  delegate_to: "{{ proxmox_node_host }}"
  ansible.builtin.lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_vmid }}.conf"
    regexp: "{{ item.regexp | default(omit) }}"
    search_string: "{{ item.regexp | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    line: "{{ item.line }}"
  loop: "{{ proxmox_ct_combined['host_extra_config'] | default([]) }}"
  when:
    - proxmox_vmid is defined
    - proxmox_ct_combined['host_extra_config'] is defined
    - proxmox_ct_combined['host_extra_config'] | length > 0
  register: ct_config_result
  notify: Restart Proxmox Container

- name: Start Proxmox Container
  delegate_to: localhost
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    vmid: "{{ proxmox_vmid }}"
    node: "{{ proxmox_node }}"
    state: started
  when:
    - proxmox_vmid is defined

- name: Wait for Proxmox Container to be ready
  delegate_to: localhost
  community.proxmox.proxmox_vm_info:
    api_host: "{{ proxmox_api_host }}"
    api_port: "{{ proxmox_api_port | default(proxmox_api_port_default) }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
    api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
    api_password: "{{ proxmox_api_password | default(omit) }}"
    node: "{{ proxmox_node }}"
    type: lxc
    vmid: "{{ proxmox_vmid }}"
  register: proxmox_vm_info
  retries: 5
  delay: 15
  until: proxmox_vm_info.proxmox_vms[0].status == 'running'
  when: not ansible_check_mode
